import 'package:flutter/material.dart';
import 'package:legend_cinema/core/themes/screen_transition.dart';
import 'presentation/routes/app_router.dart'; // Import the function that provides the map
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:provider/provider.dart';
import './presentation/state/cart_state.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CartState()),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
      pageTransitionsTheme: PageTransitionsTheme(
        builders: {
          TargetPlatform.android: CustomPageTransitionBuilder(),
          TargetPlatform.iOS: CustomPageTransitionBuilder(),
        },
      ),
    ),
      title: 'Structured Routing Demo',
      // 1. Assign the generated map of routes
      routes: getRoutes(), 
      
      // 2. Set the initial route for the application
      initialRoute: '/signUp', 

      // 3. Define the screen to display if a named route is not found (optional but good practice)
      onUnknownRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => const Scaffold(
            body: Center(
              child: Text('404 - Route Not Found'),
            ),
          ),
        );
      },
    );
  }
}