import 'package:flutter/material.dart';
import 'package:legend_cinema/core/themes/screen_transition.dart';
import 'package:legend_cinema/presentation/state/auth_state.dart';
import 'presentation/routes/app_router.dart'; // Import the function that provides the map
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:provider/provider.dart';
import './presentation/state/cart_state.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // 1. Create and initialize a SINGLE instance of AuthState
  final authState = AuthState();
  await authState.loadUserFromStorage();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CartState()),
        // 2. Provide the initialized instance to the widget tree
        ChangeNotifierProvider.value(value: authState),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(
        pageTransitionsTheme: PageTransitionsTheme(
          builders: {
            TargetPlatform.android: CustomPageTransitionBuilder(),
            TargetPlatform.iOS: CustomPageTransitionBuilder(),
          },
        ),
      ),
      title: 'Structured Routing Demo',
      routes: getRoutes(),
      initialRoute: '/cinema',
      onUnknownRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => const Scaffold(
            body: Center(child: Text('404 - Route Not Found')),
          ),
        );
      },
    );
  }
}
