import 'package:flutter/material.dart';
import 'presentation/routes/app_router.dart'; // Import the function that provides the map
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:provider/provider.dart';
import './presentation/state/cart_state.dart';

// --- START: NEW LINES ADDED FOR CINEMA SCREEN INTEGRATION ---

import 'package:cloud_firestore/cloud_firestore.dart'; // Import Firestore
import 'package:legend_cinema/data/repositories/cinema_repository.dart';
import 'package:legend_cinema/data/repositories/cinema_repository_impl.dart';
import 'package:legend_cinema/domain/usecases/get_cinemas_usecase.dart';

import 'presentation/state/cinema_state.dart';
import 'presentation/screens/cinemascreen/cinema_screen.dart';

// 1. Dependency Initialization (outside of main/build)
final FirebaseFirestore firestoreInstance = FirebaseFirestore.instance;
final CinemaRepository cinemaRepository = CinemaRepositoryImpl(firestoreInstance);
final GetCinemasUseCase getCinemasUseCase = GetCinemasUseCase(cinemaRepository);

// --- END: NEW LINES ADDED FOR CINEMA SCREEN INTEGRATION ---


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => CartState()),
        
        // --- START: NEW LINE ADDED TO PROVIDERS LIST ---
        ChangeNotifierProvider(
          // Inject the CinemaState, passing the initialized UseCase to its constructor.
          create: (_) => CinemaState(getCinemasUseCase),
        ),
        // --- END: NEW LINE ADDED TO PROVIDERS LIST ---
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Structured Routing Demo',
      // 1. Assign the generated map of routes
      routes: getRoutes(), 
      
      // 2. Set the initial route for the application
      initialRoute: '/cinema', 

      // 3. Define the screen to display if a named route is not found (optional but good practice)
      onUnknownRoute: (settings) {
        return MaterialPageRoute(
          builder: (context) => const Scaffold(
            body: Center(
              child: Text('404 - Route Not Found'),
            ),
          ),
        );
      },
    );
  }
}


void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Initialize dependencies
    final cinemaRepository = CinemaRepositoryImpl();
    final getCinemasUseCase = GetCinemasUseCase(cinemaRepository);

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(
          create: (_) => CinemaState(getCinemasUseCase),
        ),
      ],
      child: MaterialApp(
        title: 'Legend Cinema',
        theme: ThemeData(
          brightness: Brightness.dark,
          primaryColor: Colors.red,
          scaffoldBackgroundColor: const Color(0xFF1a0a0a),
        ),
        home: const CinemaScreen(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}